export default function sitemap() {
  return [
    {
      url: "https://www.textverket.se",
      lastModified: new Date("2026-06-11"),
      changeFrequency: "weekly",
      priority: 1.0,
    },
    {
      url: "https://www.textverket.se/verktyg",
      lastModified: new Date("2026-06-09"),
      changeFrequency: "weekly",
      priority: 0.9,
    },
    {
      url: "https://www.textverket.se/blogg",
      lastModified: new Date("2026-06-09"),
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: "https://www.textverket.se/blogg/offertmejl-guide",
      lastModified: new Date("2026-04-01"),
      changeFrequency: "monthly",
      priority: 0.7,
    },
    {
      url: "https://www.textverket.se/blogg/gratis-ai-verktyg",
      lastModified: new Date("2026-04-16"),
      changeFrequency: "monthly",
      priority: 0.7,
    },
    {
      url: "https://www.textverket.se/blogg/kundmejl-mallar",
      lastModified: new Date("2026-04-16"),
      changeFrequency: "monthly",
      priority: 0.7,
    },
    {
      url: "https://www.textverket.se/blogg/produktbeskrivningar-guide",
      lastModified: new Date("2026-04-16"),
      changeFrequency: "monthly",
      priority: 0.7,
    },
    {
      url: "https://www.textverket.se/blogg/betalningspaminnelse-mall",
      lastModified: new Date("2026-04-16"),
      changeFrequency: "monthly",
      priority: 0.7,
    },
    {
      url: "https://www.textverket.se/blogg/personligt-brev-cv",
      lastModified: new Date("2026-04-21"),
      changeFrequency: "monthly",
      priority: 0.7,
    },
    {
      url: "https://www.textverket.se/blogg/linkedin-profil",
      lastModified: new Date("2026-04-21"),
      changeFrequency: "monthly",
      priority: 0.7,
    },
    {
      url: "https://www.textverket.se/blogg/pressmeddelande-mall",
      lastModified: new Date("2026-04-21"),
      changeFrequency: "monthly",
      priority: 0.7,
    },
    {
      url: "https://www.textverket.se/blogg/nyhetsbrev-guide",
      lastModified: new Date("2026-04-21"),
      changeFrequency: "monthly",
      priority: 0.7,
    },
    {
      url: "https://www.textverket.se/blogg/seo-smaforetag",
      lastModified: new Date("2026-06-28"),
      changeFrequency: "monthly",
      priority: 0.7,
    },
    {
      url: "https://www.textverket.se/blogg/professionella-mejl",
      lastModified: new Date("2026-04-20"),
      changeFrequency: "monthly",
      priority: 0.7,
    },
    {
      url: "https://www.textverket.se/blogg/sociala-medier-foretag",
      lastModified: new Date("2026-04-20"),
      changeFrequency: "monthly",
      priority: 0.7,
    },
    {
      url: "https://www.textverket.se/blogg/starta-eget-vid-sidan-av-jobbet",
      lastModified: new Date("2026-04-20"),
      changeFrequency: "monthly",
      priority: 0.7,
    },
    {
      url: "https://www.textverket.se/blogg/gratis-verktyg-egenforetagare",
      lastModified: new Date("2026-04-20"),
      changeFrequency: "monthly",
      priority: 0.7,
    },
    {
      url: "https://www.textverket.se/verktyg/offertmejl",
      lastModified: new Date("2026-06-09"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: "https://www.textverket.se/verktyg/produkttext",
      lastModified: new Date("2026-06-09"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: "https://www.textverket.se/verktyg/kundmejl",
      lastModified: new Date("2026-06-09"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: "https://www.textverket.se/verktyg/sociala-medier",
      lastModified: new Date("2026-06-09"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: "https://www.textverket.se/verktyg/fakturatext",
      lastModified: new Date("2026-06-09"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: "https://www.textverket.se/verktyg/fritext",
      lastModified: new Date("2026-06-09"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: "https://www.textverket.se/om-oss",
      lastModified: new Date("2026-04-26"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: "https://www.textverket.se/kontakt",
      lastModified: new Date("2026-04-26"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: "https://www.textverket.se/guide",
      lastModified: new Date("2026-04-26"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: "https://www.textverket.se/integritetspolicy",
      lastModified: new Date("2026-04-21"),
      changeFrequency: "yearly",
      priority: 0.3,
    },
    {
      url: "https://www.textverket.se/anvandarvillkor",
      lastModified: new Date("2026-06-11"),
      changeFrequency: "yearly",
      priority: 0.3,
    },
  ];
}
